# Generated by Django 5.2.5 on 2025-11-05 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sector_perfilusuario_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes', to='core.sector')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
