# Generated by Django 5.2.5 on 2025-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='icono',
            field=models.CharField(default='🏆', max_length=50),
        ),
        migrations.AddField(
            model_name='mision',
            name='tipo',
            field=models.CharField(choices=[('diaria', 'Reto diario'), ('semanal', 'Reto semanal'), ('mensual', 'Reto mensual')], default='diaria', max_length=10),
        ),
    ]
