# Generated by Django 5.2.5 on 2025-09-22 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_mision_icono_mision_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏅', max_length=50)),
                ('tipo', models.CharField(choices=[('misiones_completadas', 'Por número de misiones completadas'), ('progreso_semanal', 'Por completar progreso semanal'), ('racha_diaria', 'Por racha de días consecutivos'), ('puntos_acumulados', 'Por acumular puntos'), ('tipo_mision', 'Por completar tipos específicos de misiones'), ('especial', 'Insignia especial')], max_length=20)),
                ('criterio_valor', models.IntegerField(help_text='Valor necesario para obtener la insignia (ej: 10 misiones)')),
                ('criterio_extra', models.CharField(blank=True, help_text='Criterio adicional si es necesario', max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de dificultad (menor = más fácil)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'criterio_valor'],
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('progreso_actual', models.IntegerField(default=0, help_text='Progreso actual hacia la insignia')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_obtenida'],
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
