# Generated by Django 5.2.5 on 2025-09-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_insignia_insigniausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignia',
            name='icono',
        ),
        migrations.AddField(
            model_name='insignia',
            name='icono_fallback',
            field=models.CharField(default='🏅', help_text='Emoji como fallback si no hay imagen', max_length=50),
        ),
        migrations.AddField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la insignia', null=True, upload_to='insignias/'),
        ),
    ]
