# Generated by Django 5.2.5 on 2025-09-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_premioruleta_ruletadiariausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruletadiariausuario',
            name='premio_obtenido',
        ),
        migrations.AlterUniqueTogether(
            name='ruletadiariausuario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ruletadiariausuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PremioRuleta',
        ),
        migrations.DeleteModel(
            name='RuletaDiariaUsuario',
        ),
    ]
