# Generated by Django 5.2.5 on 2025-09-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_remove_ruletadiariausuario_premio_obtenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignia',
            name='icono_fallback',
        ),
    ]
