# Generated by Django 5.2.5 on 2025-09-22 01:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='🎁', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recompensa',
            options={'ordering': ['categoria', 'costo_puntos']},
        ),
        migrations.AddField(
            model_name='recompensa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 22, 1, 40, 47, 937273, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recompensa',
            name='icono',
            field=models.CharField(default='🎁', max_length=50),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='stock',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.categoriarecompensa'),
        ),
        migrations.CreateModel(
            name='CompraRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_gastados', models.IntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('canjeado', models.BooleanField(default=False)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
