# Generated by Django 5.2.5 on 2025-09-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_categoriarecompensa_alter_recompensa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recompensa',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='recompensa',
            name='stock',
        ),
    ]
