# Generated by Django 5.2.5 on 2025-09-23 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_remove_recompensa_imagen_url_remove_recompensa_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('tip_laboral', 'Tip Laboral Extra'), ('acceso_curso', 'Acceso a Curso Corto'), ('magneto_50', '+50 Magneto Points'), ('magneto_80', '+80 Magneto Points'), ('invita_gana', 'Doble puntos si invitas amigo')], max_length=20)),
                ('valor', models.IntegerField(default=0, help_text='Valor del premio (puntos, etc.)')),
                ('icono', models.CharField(default='🎁', max_length=50)),
                ('probabilidad', models.FloatField(default=16.67, help_text='Probabilidad de obtener este premio (porcentaje)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden en la ruleta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RuletaDiariaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_giro', models.DateField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False, help_text='Si el premio ya fue usado/aplicado')),
                ('premio_obtenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.premioruleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'fecha_giro')},
            },
        ),
        migrations.DeleteModel(
            name='RuletaDiaria',
        ),
    ]
