# Generated by Django 5.2.5 on 2025-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='icono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('bienvenida', 'Bienvenida'), ('mision_pendiente', 'Misión pendiente'), ('recordatorio', 'Recordatorio')], default='sistema', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
