# Generated by Django 5.2.5 on 2025-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificacion_icono_alter_notificacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('bienvenida', 'Bienvenida'), ('mision_pendiente', 'Misión pendiente'), ('misiones_completadas', 'Misiones completadas'), ('tip_perfil', 'Tip de perfil'), ('recordatorio', 'Recordatorio')], default='sistema', max_length=32),
        ),
    ]
