# Generated by Django 5.2.5 on 2025-10-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='challenge_types',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de retos que le interesan'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='connection_level',
            field=models.CharField(blank=True, choices=[('starting', 'Estoy empezando'), ('occasional', 'Lo uso ocasionalmente'), ('frequent', 'Soy usuario frecuente')], help_text='Nivel de conexión con Magneto', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], help_text='Frecuencia de retos deseada', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='main_motivation',
            field=models.CharField(blank=True, choices=[('rewards', 'Ganar puntos e insignias'), ('progress', 'Ver mi progreso'), ('sharing', 'Compartir logros con otros'), ('challenge', 'Desafiarme a mí mismo')], help_text='Motivación principal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='motivating_topics',
            field=models.JSONField(blank=True, default=list, help_text='Temas que motivan al usuario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('app', 'Dentro de la app')], help_text='Método de notificaciones preferido', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='professional_stage',
            field=models.CharField(blank=True, choices=[('seeking', 'Buscando oportunidades'), ('learning', 'Aprendiendo nuevas habilidades'), ('growing', 'Creciendo en mi puesto actual')], help_text='Etapa profesional del usuario', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='survey_completed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario completó la encuesta de onboarding'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía del usuario', null=True),
        ),
    ]
